routes/web.php
<?php

Route::get('/', 'PageController@home')->name('_root_');


// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::get('pages/deleteimage/{page}', 'PageController@deleteimage')->name('pages.deleteimage');
    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::get('booking/review','AppointmentController@reviewbooking')->name('booking.review');
    Route::post('appointment/{id}/approve', 'AppointmentController@approve')->name('appointment.approve');
    Route::post('appointment/{id}/decline', 'AppointmentController@decline')->name('appointment.decline');
    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');
    Route::resource('galleries', 'GalleryController');
    Route::resource('socials', 'SocialController');
    Route::resource('admins', 'AdminController');
    Route::resource('registers', 'RegisterController');
    Route::resource('contactinfos', 'ContactInfoController');
    Route::resource('inquiryinfos', 'InquiryController');
    Route::resource('universities','UniversityController');
    Route::resource('counselor','CounselorController');
    Route::resource('times','TimeController');
    Route::resource('videos', 'VideoController');
    Route::resource('albums', 'AlbumController');
    Route::resource('services','ServiceController');
    Route::resource('events', 'EventController');
    Route::get('events/showhide/{event}', 'EventController@showhide')->name('events.showhide');
    Route::resource('subscriptions','SubscriptionController');
     Route::post('albums/photodelete', 'AlbumController@photodelete')->name('albums.photodelete');
});


Route::group(['middleware' => ['auth']], function(){
    Route::get('profile', 'UserController@profile')->name('profile');
});

Auth::routes();

$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if($page->slug == 'contact-us'){
        $router->get($page->slug, 'PageController@contact')->name('contact'); 
        $router->post($page->slug, 'PageController@contact');  
    }elseif($page->slug == 'our-services'){
        $router->get($page->slug, 'PageController@services')->name('services');
    }elseif($page->slug == 'study-abroad'){
        $router->get($page->slug, 'PageController@studyabroad')->name('study.abroad');
    }elseif($page->slug == 'entrance-preparation'){
        $router->get($page->slug, 'PageController@entrancepreparation')->name('entrance.preparation');
    }elseif($page->slug == 'test-preparation'){
        $router->get($page->slug, 'PageController@testpreparation')->name('test.preparation');
    }elseif($page->slug == 'open-bank-account'){
        $router->get($page->slug, 'PageController@openbankaccount')->name('open.bankaccount');
    }elseif($page->slug == 'universities'){
        $router->get($page->slug, 'PageController@universities')->name('universities');
    }
     elseif($page->slug == 'videos'){
        $router->get($page->slug, 'PageController@galleryvideo')->name('video');
    }
    elseif($page->slug == 'photos'){
        $router->get($page->slug, 'PageController@photoAlbum')->name('photo');
    }
    elseif($page->slug == 'activities'){
        $router->get($page->slug, 'PageController@activities')->name('activities');
    }elseif($page->slug == 'book-an-appointment'){
        $router->get($page->slug, 'PageController@makeappointment')->name('appointment');
    }elseif($page->slug <> '/'){
        $router->get($page->slug, 'PageController@index');
        $router->post($page->slug, 'PageController@index');
    }
   
}

Route::get('study-abroad/{slug}','PageController@studyplace')->name('study.place');
Route::post('inquiry', 'PageController@inquiry')->name('inquiry');
// Route::post('space_register', 'PageController@space_register')->name('space_register');
Route::get('captcha.jpg', 'CaptchaController@image')->name('captcha');
Route::get('thankyou', 'PageController@thankyou')->name('thankyou');

Route::get('writereviews','PageController@writereview')->name('writereview');
Route::post('writereviews','PageController@savereview')->name('savereview');
Route::get('appointment','PageController@makeappointment')->name('appointment');
Route::post('appointmentstore','BookingController@store')->name('saveappointments');
Route::get('thankyoureview', 'PageController@thankyoureview')->name('thankyoureview');
Route::get('photo-album/{id}', 'PageController@album')->name('viewalbum');
 Route::post('dynamic_dependent/fetch',[
        'as'=>'dynamindependent.fetch_location','uses'=>'PageController@fetchlocation'
    ]);
Route::post('dynamic_dependent/fetchtime',[
    'as'=>'dynamindependent.fetch_time','uses'=>'PageController@fetchtime'
]);

Route::get('service/{id}', 'PageController@viewservice')->name('viewservice');

  Route::post('dynamic_dependent/fetchuniversity',[
        'as'=>'dynamindependent.fetch_university','uses'=>'PageController@fetchuniversity'
    ]);
Route::get('activity/{id}', 'PageController@viewactivity')->name('view.activities');
Route::post('subscription','SubscriptionController@subscribe')->name('subscription.subscribe');
Route::post('unsubscribion','SubscriptionController@unsubscribe')->name('subscription.unsubscribe');
//Preview email on brower
Route::get('emailview/{id}', function($id) {
    $tablebook = \App\Order::find($id);
    return new \App\Mail\NewOrder($tablebook);
});

resources/views/admin/inquiryinfo/create.blade.php
@extends('admin.app')

@section('title')
Add Inquiry Info
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('inquiryinfos.store') }}" accept-charset="utf-8" method="post">
		{!! csrf_field() !!}

		@include('admin.inquiryinfo.form')
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/inquiryinfo/edit.blade.php
@extends('admin.app')

@section('title')
Edit Inquiry Info
@endsection

@section('content')

<div class="content-form">
	<form class="form-horizontal" action="{{ route('inquiryinfos.update', $inquiryinfo->id) }}" accept-charset="utf-8" method="post">
		{{ method_field('PUT') }}
		{!! csrf_field() !!}

		@include('admin.inquiryinfo.form')
		
		<div class="form-group">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
		</div>	
	</form>
</div>
@endsection

resources/views/admin/inquiryinfo/form.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label" for="name">Name</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Name" name="name" value="{{ old('name', isset($contactinfo) ? $contactinfo->name : null) }}" type="text" id="name" >
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="email">Email</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Email" name="email" value="{{ old('email', isset($contactinfo) ? $contactinfo->email : null) }}" type="email" id="email" >
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="Address">Address</label>
	<div class="col-sm-8">
		<textarea rows="5" class="form-control" placeholder="Address" name="address" id="address">{{ old('address', isset($contactinfo) ? $contactinfo->address : null) }}</textarea>
	</div>
</div>



<div class="form-group">
	<label class="col-sm-2 control-label" for="phone">Phone</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Phone" name="phone" value="{{ old('phone', isset($contactinfo) ? $contactinfo->phone : null) }}" type="text" id="phone" >
	</div>
</div>

<div class="form-group sec-right">
	<label class="col-sm-2 control-label contact-form-text">Select Country</label>
	<div class="col-sm-6">
	<select name="country" class="form-control">
		<option value="">---- SELECT ----</option>
		@foreach ($countries as $country)
			<option value="{{ $country->id }}">{{ $country->name }}</option>
		@endforeach
	</select>
	</div>
</div>
<div class="form-group sec-right">
	<label class="col-sm-2 control-label contact-form-text">Select Services</label>
	<div class="col-sm-6">
	<select name="service" class="form-control">
		<option value="">--------- SELECT ---------</option>
		@foreach ($services as $service)
			<option value="{{ $service->title }}">{{ $service->title }}</option>
		@endforeach
	</select>
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="message">Message</label>
	<div class="col-sm-8">
		<textarea rows="5" class="form-control" placeholder="Message" name="message" id="message">{{ old('message', isset($inquiryinfo) ? $inquiryinfo->message : null) }}</textarea>
	</div>
</div>

resources/views/admin/inquiryinfo/index.blade.php
@extends('admin.app')

@section('title')
Inquiry Info
@endsection

@section('content')

<div class="add-new">
	<a href="{{ route('inquiryinfos.create') }}" class="btn btn-primary"><i class="lnr lnr-plus-circle"></i> <span>Add New</span></a>
</div>

<div class="content-table">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>SN</th>
				<th>Name</th>
				<th>Email</th>
				<th>Phone</th>
				<th>Address</th>
				<th>Inquiry Date</th>
			</tr>
		</thead>
		<tbody>
		<?php $i=1; ?>
			@foreach ($inquiryinfos as $inquiryinfo)
			<tr>
				<td>{{$i}}</td>
				<td>{{ $inquiryinfo->name }}</td>
				<td>{{$inquiryinfo->email}}</td>
				<td>{{ $inquiryinfo->phone }}</td>
				<td>{{ $inquiryinfo->address }}</td>
				<td>{{ $inquiryinfo->created_at->format('M d, Y') }}</td>
				<td class="text-right">
					<a href="{{ route('inquiryinfos.show', $inquiryinfo->id) }}" class="btn btn-warning btn-xs"><i class="lnr lnr-eye"></i></a>
						<a class="btn btn-primary btn-sm" href="{{ route('inquiryinfos.edit', $inquiryinfo->id) }}"><i class="lnr lnr-pencil"></i></a>

						<div class="pull-right" style="margin-left: 10px;"> 
							<form onsubmit="return confirm('Are you sure?')" action="{{ route('inquiryinfos.destroy', $inquiryinfo->id) }}" method="post">
								{{ method_field('DELETE') }}
								{{ csrf_field() }}		
								<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
							</form>
						</div>
				</td>
			</tr>
				<?php $i++; ?>
			@endforeach
		</tbody>
	</table>
</div>
@endsection

resources/views/admin/inquiryinfo/view.blade.php
@extends('admin.app')

@section('title')
Inquiry Info
@endsection

@section('content')
<h3 class="page-title">Inquiry Info of <b>{{ $inquiryinfo->name }}</b> <a href="{{ route('inquiryinfos.index') }}" class="btn btn-primary pull-right"><span><i class="lnr lnr-arrow-left"></i> Back</span></a></h3>

<div class="panel">
	<div class="panel-body">
		<div class="table">
			<div>
				<label>Name:</label>
				<p>{{ $inquiryinfo['name'] }}</p>
			</div>

			<div>
				<label>Email:</label>
				<p>{{ $inquiryinfo->email }}</p>
			</div>

			<div>
				<label>Phone No:</label>
				<p>{{ $inquiryinfo->phone }}</p>
			</div>

			<div>
				<label>Address:</label>
				<p>{{ $inquiryinfo->address }}</p>
			</div>

			<div>
				<label>Country:</label>
				<p>{{ $inquiryinfo->country->code }} - {{ $inquiryinfo->country->name}}</p>
			</div>

			<div>
				<label>Service Selected:</label>
				<p>{{ $inquiryinfo->service_title }}</p>
			</div>

			<div>
				<label>Message:</label>
				<p>{{ $inquiryinfo->message }}</p>
			</div>
		</div>
	</div>
</div>
@endsection